CREATE TABLE [cuenta](
    [id] INTEGER PRIMARY KEY,
    [tipo] INTEGER NOT NULL,
    [usuario] TEXT NOT NULL,
    [e_mail] TEXT NOT NULL,
    [password] TEXT NOT NULL,
    [Pin] TEXT,
    [JSON1] TEXT ,
    [JSON2] TEXT ,
    [JSON3] TEXT ,
    [JSON4] TEXT,
    [JSON5] TEXT ,
    [JSON6] TEXT ,
    [JSON7] TEXT ,
    [JSON8] TEXT,
    [JSON9] TEXT ,
    [JSON10] TEXT ,
    [JSON11] TEXT ,
    [JSON12] TEXT,
    [JSON13] TEXT ,
    [JSON14] TEXT ,
    [EXTRA1] TEXT ,
    [EXTRA2] TEXT
    );